### ISSUE TITLE
TSD start-workflow.sh issues

### ISSUE THREAD

**Issue by daviddolan** [elixir-no-nels/Selma#13]
Hi

I've come across some issues with the start-workflow.sh script on TSD

One wherever it sends the fastq files on colossus has a limit on how much can be uploaded to there.

The test files I'm using are about 30Gb each and the slurm job gives up before finishing the transfer of the R1 file.

Secondly I've noted that when moving the files to the staging area (and presumably when sending stuff up to colossus) the script takes every file in the input folder not just the ones defined in the sample table tsv. This can make run/upload times needlessly long if there are a lot of fastqs in the input location.

All the best

David

**Comment by oskarvid** [comment]
There is a fix for the second issue in the next release, it's easy to
backport it.

But the first issue is perplexing, I'll be back on the 20th to take a close
look at it.

Regards
/Oskar

**Comment by oskarvid** [comment]
@daviddolan, how much data did you send to Colossus when you hit the limit?

**Comment by oskarvid** [comment]
After communicating with Kjell and David it seems like this issue was a problem on the TSD side that has been resolved now. 
Since the file transfer issue already has a fix that only needs to be backported I will close this issue now.
