### ISSUE TITLE
Enhance documentation of -s option

### ISSUE THREAD

**Issue by kjellp** [elixir-no-nels/Selma#20]
Suggest to add "to run the workflow analysis in parallel." to the end of the help/usage text. This will also indicate that not using the "-s" flag, will run the samples sequentially on a single node.

**Comment by oskarvid** [comment]
Changed help text in [commit df78b14](https://github.com/elixir-no-nels/Selma/commit/df78b14171477fdb8fade57cf94c8ac0814854ed).
