### ISSUE TITLE
Input folder requirements

### ISSUE THREAD

**Issue by kjellp** [elixir-no-nels/Selma#22]
Currently the code requires some fastq files resides in the root folder of the input folder, while others may be further organized into subfolders. We need to support a top level input folder, with multiple sub folders (separating samples, runs, flowcells) in a logical way, and no fastq files present at the top level.

**Comment by oskarvid** [comment]
That's an easy fix, I just need to use find instead of compgen, we'll
implement it in release 3.

**Comment by oskarvid** [comment]
I decided to add it in milestone 2 anyways.
